// FILE: src/lib/india-locations.ts
// Complete update — sabhi states mein major cities added

export const INDIA_STATES = [
    'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar',
    'Chhattisgarh', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
    'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra',
    'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
    'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
    'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
    'Andaman and Nicobar Islands', 'Chandigarh', 'Dadra and Nagar Haveli',
    'Daman and Diu', 'Delhi', 'Jammu and Kashmir', 'Ladakh',
    'Lakshadweep', 'Puducherry',
]

export const STATE_CITIES: Record<string, string[]> = {
    'Andhra Pradesh': [
        'Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore', 'Kurnool',
        'Tirupati', 'Kakinada', 'Rajahmundry', 'Kadapa', 'Anantapur',
        'Vizianagaram', 'Eluru', 'Ongole', 'Nandyal', 'Machilipatnam',
        'Adoni', 'Tenali', 'Chittoor', 'Hindupur', 'Bhimavaram',
        'Madanapalle', 'Guntakal', 'Dharmavaram', 'Gudivada', 'Narasaraopet',
        'Tadipatri', 'Tadepalligudem', 'Chilakaluripet', 'Amaravati',
    ],
    'Arunachal Pradesh': [
        'Itanagar', 'Naharlagun', 'Pasighat', 'Tezpur', 'Bomdila',
        'Ziro', 'Along', 'Tezu', 'Roing', 'Namsai',
        'Changlang', 'Khonsa',
    ],
    'Assam': [
        'Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Nagaon',
        'Tinsukia', 'Tezpur', 'Bongaigaon', 'Dhubri', 'Diphu',
        'North Lakhimpur', 'Sivasagar', 'Goalpara', 'Karimganj',
        'Golaghat', 'Haflong', 'Kokrajhar', 'Nalbari', 'Barpeta',
        'Mangaldoi', 'Mushalpur', 'Rangia',
    ],
    'Bihar': [
        'Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Darbhanga',
        'Purnia', 'Arrah', 'Begusarai', 'Katihar', 'Munger',
        'Chapra', 'Hajipur', 'Sasaram', 'Jehanabad', 'Buxar',
        'Siwan', 'Samastipur', 'Motihari', 'Sitamarhi', 'Supaul',
        'Saharsa', 'Madhepura', 'Kishanganj', 'Aurangabad', 'Nawada',
        'Jamui', 'Bettiah', 'Dehri', 'Chhapra', 'Forbesganj',
        'Khagaria', 'Lakhisarai', 'Sheikhpura', 'Sheohar',
    ],
    'Chhattisgarh': [
        'Raipur', 'Bhilai', 'Korba', 'Bilaspur', 'Durg',
        'Rajnandgaon', 'Jagdalpur', 'Raigarh', 'Ambikapur', 'Dhamtari',
        'Chirmiri', 'Bhatapara', 'Mahasamund', 'Kanker', 'Kawardha',
        'Bijapur', 'Narayanpur', 'Balod', 'Gariaband', 'Kondagaon',
        'Jashpur Nagar', 'Surajpur', 'Balrampur',
    ],
    'Goa': [
        'Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda',
        'Bicholim', 'Curchorem', 'Sanquelim', 'Valpoi', 'Pernem',
        'Quepem', 'Canacona', 'Calangute', 'Candolim', 'Colva',
    ],
    'Gujarat': [
        'Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar',
        'Jamnagar', 'Junagadh', 'Gandhinagar', 'Anand', 'Navsari',
        'Morbi', 'Nadiad', 'Surendranagar', 'Mehsana', 'Bharuch',
        'Valsad', 'Amreli', 'Godhra', 'Patan', 'Dahod',
        'Porbandar', 'Veraval', 'Botad', 'Dwarka', 'Palitana',
        'Palanpur', 'Himatnagar', 'Deesa', 'Wankaner', 'Gondal',
        'Jetpur', 'Mahuva', 'Vyara', 'Ankleshwar', 'Kheda',
    ],
    'Haryana': [
        'Faridabad', 'Gurgaon', 'Panipat', 'Ambala', 'Yamunanagar',
        'Rohtak', 'Hisar', 'Karnal', 'Sonipat', 'Panchkula',
        'Bhiwani', 'Sirsa', 'Bahadurgarh', 'Jind', 'Thanesar',
        'Kaithal', 'Rewari', 'Palwal', 'Fatehabad', 'Mahendragarh',
        'Nuh', 'Narnaul', 'Hansi', 'Shahabad', 'Dabwali',
        'Pehowa', 'Ratia', 'Gohana', 'Sohna', 'Manesar',
    ],
    'Himachal Pradesh': [
        'Shimla', 'Mandi', 'Solan', 'Dharamsala', 'Kullu',
        'Baddi', 'Nahan', 'Paonta Sahib', 'Sundernagar', 'Chamba',
        'Hamirpur', 'Una', 'Bilaspur', 'Kangra', 'Keylong',
        'Recong Peo', 'Rampur', 'Nurpur', 'Jogindernagar',
    ],
    'Jharkhand': [
        'Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Deoghar',
        'Phusro', 'Hazaribagh', 'Giridih', 'Ramgarh', 'Medininagar',
        'Chirkunda', 'Chaibasa', 'Daltonganj', 'Dumka', 'Godda',
        'Pakur', 'Sahibganj', 'Gumla', 'Simdega', 'Lohardaga',
        'Jamtara', 'Khunti', 'Latehar',
    ],
    'Karnataka': [
        'Bengaluru', 'Mysuru', 'Hubballi', 'Mangaluru', 'Belagavi',
        'Kalaburagi', 'Ballari', 'Vijayapura', 'Shivamogga', 'Tumkur',
        'Davanagere', 'Udupi', 'Hassan', 'Dharwad', 'Bidar',
        'Raichur', 'Koppal', 'Gadag', 'Haveri', 'Bagalkot',
        'Chitradurga', 'Chamarajanagar', 'Mandya', 'Chikkamagaluru',
        'Chikkaballapur', 'Ramanagara', 'Kolar', 'Yadgir', 'Kodagu',
        'Robertsonpet', 'Hospet', 'Gangawati', 'Ranebennuru',
        'Bhadravati', 'Tiptur',
    ],
    'Kerala': [
        'Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Thrissur', 'Kollam',
        'Palakkad', 'Alappuzha', 'Malappuram', 'Kannur', 'Kasaragod',
        'Kottayam', 'Idukki', 'Pathanamthitta', 'Wayanad', 'Ernakulam',
        'Aluva', 'Perinthalmanna', 'Manjeri', 'Tirur', 'Ponnani',
        'Vatakara', 'Koyilandy', 'Thalassery', 'Payyanur', 'Irinjalakuda',
        'Chalakudy', 'Muvattupuzha', 'Kothamangalam', 'Changanacherry',
        'Pala', 'Thodupuzha', 'Adoor',
    ],
    'Madhya Pradesh': [
        'Bhopal', 'Indore', 'Jabalpur', 'Gwalior', 'Ujjain',
        'Sagar', 'Ratlam', 'Satna', 'Dewas', 'Murwara',
        'Chhindwara', 'Rewa', 'Singrauli', 'Burhanpur', 'Khandwa',
        'Bhind', 'Shivpuri', 'Vidisha', 'Sehore', 'Hoshangabad',
        'Itarsi', 'Neemuch', 'Mandsaur', 'Chhatarpur', 'Tikamgarh',
        'Datia', 'Morena', 'Guna', 'Ashok Nagar', 'Sheopur',
        'Dhar', 'Barwani', 'Alirajpur', 'Jhabua', 'Rajgarh',
        'Shajapur', 'Agar Malwa', 'Narsinghpur', 'Seoni', 'Mandla',
        'Dindori', 'Balaghat', 'Katni', 'Umaria', 'Anuppur',
        'Sidhi', 'Panna',
    ],
    'Maharashtra': [
        'Mumbai', 'Pune', 'Nagpur', 'Thane', 'Nashik',
        'Aurangabad', 'Solapur', 'Kolhapur', 'Amravati', 'Nanded',
        'Sangli', 'Malegaon', 'Jalgaon', 'Akola', 'Latur',
        'Dhule', 'Ahmednagar', 'Chandrapur', 'Parbhani', 'Ichalkaranji',
        'Jalna', 'Ambernath', 'Bhiwandi', 'Shirdi', 'Panvel',
        'Kalyan', 'Dombivali', 'Vasai', 'Virar', 'Mira Road',
        'Ulhasnagar', 'Navi Mumbai', 'Satara', 'Ratnagiri', 'Sindhudurg',
        'Gondia', 'Bhandara', 'Wardha', 'Yavatmal', 'Washim',
        'Buldhana', 'Hingoli', 'Osmanabad', 'Bid', 'Raigad',
        'Alibag',
    ],
    'Manipur': [
        'Imphal', 'Thoubal', 'Kakching', 'Churachandpur', 'Bishnupur',
        'Senapati', 'Ukhrul', 'Tamenglong', 'Jiribam', 'Moreh',
    ],
    'Meghalaya': [
        'Shillong', 'Tura', 'Nongstoin', 'Jowai', 'Baghmara',
        'Williamnagar', 'Resubelpara', 'Ampati', 'Nongpoh',
    ],
    'Mizoram': [
        'Aizawl', 'Lunglei', 'Champhai', 'Serchhip', 'Kolasib',
        'Lawngtlai', 'Saiha', 'Mamit',
    ],
    'Nagaland': [
        'Kohima', 'Dimapur', 'Mokokchung', 'Tuensang', 'Wokha',
        'Zunheboto', 'Phek', 'Mon', 'Longleng', 'Kiphire',
        'Peren',
    ],
    'Odisha': [
        'Bhubaneswar', 'Cuttack', 'Rourkela', 'Brahmapur', 'Sambalpur',
        'Puri', 'Balasore', 'Bhadrak', 'Baripada', 'Jharsuguda',
        'Bargarh', 'Angul', 'Dhenkanal', 'Kendrapara', 'Keonjhar',
        'Sundargarh', 'Bolangir', 'Koraput', 'Phulbani', 'Jagatsinghpur',
        'Rayagada', 'Bhawanipatna', 'Nabarangpur', 'Malkangiri',
        'Nuapada', 'Sonepur', 'Khordha', 'Nayagarh', 'Jajapur',
    ],
    'Punjab': [
        'Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda',
        'Mohali', 'Firozpur', 'Batala', 'Pathankot', 'Moga',
        'Sangrur', 'Hoshiarpur', 'Gurdaspur', 'Muktsar', 'Barnala',
        'Faridkot', 'Fazilka', 'Ferozepur', 'Kapurthala', 'Nawanshahr',
        'Rupnagar', 'Tarn Taran', 'Fatehgarh Sahib', 'Mansa', 'Malerkotla',
        'Abohar', 'Phagwara', 'Khanna', 'Zirakpur', 'Rajpura',
        'Dera Bassi', 'Morinda', 'Sunam',
    ],
    'Rajasthan': [
        'Jaipur', 'Jodhpur', 'Kota', 'Bikaner', 'Ajmer',
        'Udaipur', 'Bhilwara', 'Alwar', 'Bharatpur', 'Sikar',
        'Pali', 'Sri Ganganagar', 'Tonk', 'Barmer', 'Jaisalmer',
        'Jhunjhunu', 'Churu', 'Hanumangarh', 'Dholpur', 'Dausa',
        'Sawai Madhopur', 'Nagaur', 'Bundi', 'Karauli', 'Baran',
        'Jhalawar', 'Rajsamand', 'Banswara', 'Dungarpur', 'Pratapgarh',
        'Sirohi', 'Jalor', 'Chittorgarh', 'Mandor', 'Beawar',
        'Kishangarh', 'Makrana', 'Sambhar',
    ],
    'Sikkim': [
        'Gangtok', 'Namchi', 'Gyalshing', 'Mangan', 'Rangpo',
        'Jorethang', 'Nayabazar', 'Ravangla',
    ],
    'Tamil Nadu': [
        'Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem',
        'Tirunelveli', 'Tiruppur', 'Vellore', 'Erode', 'Thoothukkudi',
        'Dindigul', 'Thanjavur', 'Ranipet', 'Sivakasi', 'Karur',
        'Udhagamandalam', 'Hosur', 'Nagercoil', 'Kanchipuram', 'Kumarapalayam',
        'Karaikkudi', 'Neyveli', 'Cuddalore', 'Kumbakonam', 'Nagapattinam',
        'Viluppuram', 'Krishnagiri', 'Dharmapuri', 'Ariyalur', 'Perambalur',
        'Pudukkottai', 'Ramanathapuram', 'Virudhunagar', 'Namakkal',
        'Tiruvallur', 'Kanyakumari', 'Tiruvanamalai', 'Chengalpattu',
        'Mayiladuthurai', 'Kallakurichi',
    ],
    'Telangana': [
        'Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Khammam',
        'Ramagundam', 'Mahbubnagar', 'Nalgonda', 'Adilabad', 'Suryapet',
        'Miryalaguda', 'Siddipet', 'Jagtial', 'Mancherial', 'Nirmal',
        'Kothagudem', 'Bhongir', 'Vikarabad', 'Wanaparthy', 'Nagarkurnool',
        'Sangareddy', 'Medak', 'Kamareddy', 'Peddapalli', 'Jangaon',
        'Mahabubabad', 'Bhadradri Kothagudem', 'Yadadri Bhongir',
        'Mulugu', 'Narayanpet', 'Narayankhed',
    ],
    'Tripura': [
        'Agartala', 'Udaipur', 'Dharmanagar', 'Kailasahar', 'Belonia',
        'Sabroom', 'Khowai', 'Teliamura', 'Ambassa',
    ],
    'Uttar Pradesh': [
        'Lucknow', 'Kanpur', 'Agra', 'Varanasi', 'Meerut',
        'Allahabad', 'Bareilly', 'Aligarh', 'Moradabad', 'Gorakhpur',
        'Noida', 'Ghaziabad', 'Firozabad', 'Jhansi', 'Saharanpur',
        'Mathura', 'Muzaffarnagar', 'Rampur', 'Shahjahanpur', 'Sitapur',
        'Lakhimpur', 'Unnao', 'Rae Bareli', 'Hardoi', 'Etawah',
        'Mainpuri', 'Budaun', 'Sambhal', 'Amroha', 'Hapur',
        'Hathras', 'Kasganj', 'Etah', 'Farrukhabad', 'Kannauj',
        'Auraiya', 'Jalaun', 'Hamirpur', 'Mahoba', 'Banda',
        'Chitrakoot', 'Fatehpur', 'Kaushambi', 'Pratapgarh', 'Sultanpur',
        'Faizabad', 'Ambedkar Nagar', 'Bahraich', 'Shravasti', 'Balrampur',
        'Gonda', 'Basti', 'Sant Kabir Nagar', 'Siddharth Nagar',
        'Maharajganj', 'Kushinagar', 'Deoria', 'Mau', 'Azamgarh',
        'Ballia', 'Jaunpur', 'Ghazipur', 'Chandauli', 'Sant Ravidas Nagar',
        'Mirzapur', 'Sonbhadra', 'Pilibhit',
    ],
    'Uttarakhand': [
        'Dehradun', 'Haridwar', 'Roorkee', 'Haldwani', 'Rudrapur',
        'Kashipur', 'Rishikesh', 'Nainital', 'Almora', 'Pithoragarh',
        'Mussoorie', 'Kotdwar', 'Ramnagar', 'Srinagar', 'Pauri',
        'Tehri', 'Uttarkashi', 'Chamoli', 'Gopeshwar', 'Joshimath',
        'Lansdowne', 'Champawat', 'Bageshwar',
    ],
    'West Bengal': [
        'Kolkata', 'Howrah', 'Asansol', 'Siliguri', 'Durgapur',
        'Bardhaman', 'Malda', 'Baharampur', 'Habra', 'Kharagpur',
        'Shantipur', 'Dankuni', 'Dhulian', 'Ranaghat', 'Haldia',
        'Raiganj', 'Krishnanagar', 'Nabadwip', 'Medinipur', 'Bankura',
        'Bishnupur', 'Balurghat', 'Jangipur', 'Cooch Behar', 'Alipurduar',
        'Jalpaiguri', 'Darjeeling', 'Kalimpong', 'Purulia', 'Jhargram',
        'Serampore', 'Chandannagar', 'Kamarhati', 'Bally', 'Barrackpore',
        'Barasat', 'Dum Dum', 'Bidhannagar', 'South Dum Dum',
        'Titagarh', 'Panihati', 'Naihati', 'Uttarpara',
    ],
    'Delhi': [
        'New Delhi', 'Dwarka', 'Rohini', 'Pitampura', 'Janakpuri',
        'Saket', 'Lajpat Nagar', 'Karol Bagh', 'Connaught Place',
        'Shahdara', 'Preet Vihar', 'Mayur Vihar', 'Vasant Kunj',
        'Vasant Vihar', 'Greater Kailash', 'Sarita Vihar', 'Nehru Place',
        'Rajouri Garden', 'Paschim Vihar', 'Uttam Nagar', 'Tilak Nagar',
        'Vikaspuri', 'Najafgarh', 'Narela', 'Bawana', 'Mundka',
        'Nangloi', 'Mustafabad', 'Dilshad Garden', 'Geeta Colony',
        'Krishna Nagar', 'Laxmi Nagar', 'Noida Extension', 'Burari',
    ],
    'Jammu and Kashmir': [
        'Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Sopore',
        'Kathua', 'Udhampur', 'Pulwama', 'Budgam', 'Kupwara',
        'Ganderbal', 'Bandipora', 'Kulgam', 'Shopian', 'Ramban',
        'Doda', 'Kishtwar', 'Rajouri', 'Poonch', 'Reasi',
        'Samba', 'Akhnoor',
    ],
    'Ladakh': [
        'Leh', 'Kargil', 'Diskit', 'Padum', 'Nyoma',
    ],
    'Chandigarh': [
        'Chandigarh', 'Manimajra', 'Panchkula', 'Mohali',
        'Sector 17', 'Sector 22', 'Sector 35',
    ],
    'Puducherry': [
        'Puducherry', 'Karaikal', 'Mahe', 'Yanam', 'Oulgaret',
    ],
    'Andaman and Nicobar Islands': [
        'Port Blair', 'Diglipur', 'Rangat', 'Mayabunder', 'Car Nicobar',
    ],
    'Dadra and Nagar Haveli': [
        'Silvassa', 'Amli', 'Khanvel', 'Naroli',
    ],
    'Daman and Diu': [
        'Daman', 'Diu', 'Moti Daman', 'Nani Daman',
    ],
    'Lakshadweep': [
        'Kavaratti', 'Agatti', 'Minicoy', 'Amini', 'Andrott',
    ],
}